# Load Balancer Configuration
compartment_id: "ocid1.compartment.oc1..aaaaaaaape26buh5zkbujozgyrlecuplate5qvmllg3ym3ajotrz4q2q6yzq"

load_balancer_map:
  - display_name: "example-web-lb"
    shape: "flexible"
    shape_details:
      minimum_bandwidth_in_mbps: 10
      maximum_bandwidth_in_mbps: 100
    subnet_ids: 
      - "ocid1.subnet.oc1.eu-frankfurt-1.aaaaaaaadljwjyhxjx3ejt6w5nrzlpp5bun5qyxvv6ccc2zmtn3zcnjnzusq"
    is_private: false
    defined_tags: {}

backend_set_map:
  - display_name: "web-backend-set"
    load_balancer_name: "example-web-lb"
    protocol: "HTTP"
    health_check_protocol: "HTTP"
    health_check_port: 80
    health_check_path: "/"
    health_check_interval_ms: 10000
    health_check_timeout_ms: 3000
    health_check_retries: 3
    lb_cookie_session_persistence_enabled: true
    session_persistence_cookie_name: "CUSTOM_LB_COOKIE"

backend_map:
  - backend_set_name: "web-backend-set"
    load_balancer_name: "example-web-lb"
    backend_target_id: "ocid1.instance.oc1.eu-frankfurt-1.antheljsvk7qqvacskvnebso6hwclz2lpylrxstynjht4xrli2iqxfe7fgfq"
    backend_port: 80
    weight: 1
  - backend_set_name: "web-backend-set"
    load_balancer_name: "example-web-lb"
    backend_target_id: "ocid1.instance.oc1.eu-frankfurt-1.antheljsvk7qqvacy3a5s4ovnjhsnxcyqoy5vhjev33tlmyod5nsmghlmhyq"
    backend_port: 80
    weight: 1

listener_map:
  - listener_name: "http-listener"
    load_balancer_name: "example-web-lb"
    backend_set_name: "web-backend-set"
    port: 80
    protocol: "HTTP"